#echo '127.0.0.1 moar.sshilko.com' >> /etc/hosts
version: "3.7"
services:
    jekyll:
        image: jekyll/jekyll:3.8
        command: jekyll serve --force_polling --watch -P 80 --livereload --trace --config _local.yml
        ports:
            - "80:80/tcp"
        volumes:
            - .:/srv/jekyll
        restart: "no"